### Ce este un Perceptron?

Un perceptron este cel mai simplu tip de neuron artificial. Gândește-te la el ca la o mașinărie minusculă care ia decizii de tip "Da" sau "Nu" (1 sau 0).

Să zicem că perceptronul trebuie să decidă dacă ieși afara.

* **Intrările (Inputs/Fetures):** Sunt informațiile pe care le primește. De exemplu: "Plouă afară?" și "Ai timp liber?".
* **Ponderile (Weights):** Cât de importantă este fiecare informație pentru tine. Poate urăști ploaia (pondere negativă mare), dar ai foarte mult timp liber (pondere pozitivă).
* **Bias-ul (Pragul):** Lenea ta naturală. Cât de greu este să te ridici din pat în general, indiferent de vreme.

Perceptronul adună toate aceste informații, le cântărește, adună bias-ul, iar dacă rezultatul depășește un anumit prag, decizia este 1 ("Ies la plimbare!"). Altfel, este 0 ("Stau în casă!").

---

### Reprezentarea matematică

Pentru a pune neuronul să calculeze, traducem exemplul de mai sus într-o formulă matematică.

Avem următoarele elemente:

* $A$: Datele de intrare (informațiile noastre).
* $W$: Ponderile (importanța fiecărei informații).
* $b$: Bias-ul (pragul de bază).

Perceptronul funcționează în doi pași simpli:

**1. Combinația liniară**
Neuronul înmulțește fiecare intrare cu ponderea ei și adună bias-ul.


$$z = A \cdot W + b$$

**2. Funcția de activare**
Neuronul ia rezultatul $z$ și îl trece printr-o funcție pentru a lua decizia finală, $\hat{y}$. Cel mai des folosim o funcție treaptă (Step Function): dacă rezultatul e pozitiv, zice Da (1). Dacă e negativ, zice Nu (0).


$$\hat{y} = \begin{cases}  1 & \text{dacă } z \geq 0 \\ 0 & \text{dacă } z < 0  \end{cases}$$



### Exercițiu 1: Implementarea formulei $A \cdot W + b$

In [ ]:
import numpy as np

# A: 3 exemple (zile diferite), fiecare cu 2 informații (ex: plouă, timp liber)
A = np.array([[1.5, 2.0],
              [2.0, 1.0],
              [3.5, 3.0]])

# W: 2 ponderi (cât de mult contează fiecare din cele 2 informații)
W = np.array([0.5, -0.2])

# b: Bias-ul nostru (un singur număr)
b = 0.1


In [ ]:

def combinatia_liniara(A, W, b):
    """
    Calculează înmulțirea matricială dintre intrări și ponderi, apoi adună bias-ul.
    """
    # TODO: Implementează formula z = A * W + b folosind numpy
    z = None

    return z

### De ce avem nevoie de Funcții de Activare?

Până acum am calculat $z = A \cdot W + b$. Acest rezultat $z$ poate fi absolut orice număr (ex: -150, 0.5 sau 9000). Dar noi avem nevoie ca neuronul să ia o decizie clară între două opțiuni (ex: 0 sau 1, "Nu" sau "Da").

**Funcția de activare** este filtrul final. Ea ia acest număr brut $z$ și îl transformă într-un format util pentru decizia noastră. Pe ultimul strat al unui model cu decizie binară folosim de obicei una dintre următoarele trei funcții:

### 1. Funcția Treaptă (Step Function)

Este cea mai simplă formă de decizie. Funcționează exact ca un întrerupător de bec: e pornit sau oprit. Dacă valoarea lui $z$ este zero sau pozitivă, rezultatul este 1. Dacă este sub zero, rezultatul este 0.

$$f(z) = \begin{cases}  1 & \text{dacă } z \ge 0 \\ 0 & \text{dacă } z < 0  \end{cases}$$

In [ ]:

import numpy as np
import matplotlib.pyplot as plt

def step_function(z):
    # np.where verifică condiția: dacă z >= 0 pune 1, altfel pune 0
    return np.where(..., ..., ...)

# Generăm numere de la -10 la 10 pentru a desena graficul
z_valori = np.linspace(-10, 10, 100)
y_treapta = step_function(z_valori)

plt.plot(z_valori, y_treapta, linewidth=3, color='blue')
plt.title("Funcția Treaptă (Step)")
plt.grid(True)
plt.show()

### 2. Funcția Semn (Sign/Signum Function)

Este aproape identică cu funcția treaptă, diferența fiind că în loc de 0, returnează -1 pentru valorile negative. Este folosită exact pentru aceleași tipuri de probleme, dar atunci când datele tale sunt etichetate matematic cu -1 (clasa negativă) și 1 (clasa pozitivă).

$$f(z) = \begin{cases}  1 & \text{dacă } z \ge 0 \\ -1 & \text{dacă } z < 0  \end{cases}$$


In [ ]:
def sign_function(z):
    return np.where(..., ..., ...)

y_semn = sign_function(z_valori)

plt.plot(z_valori, y_semn, linewidth=3, color='red')
plt.title("Funcția Semn (Sign)")
plt.grid(True)
plt.show()

### 3. Funcția Sigmoid (Logistică)

Funcțiile Treaptă și Semn sunt bruște – trec instant de la o extremă la alta. Asta ne dă o decizie dură, dar nu ne spune *cât de sigur* este modelul.

Aici intervine **Sigmoidul**. Această funcție "turtește" orice număr $z$ (oricât de mare sau mic) într-un interval cuprins strict între 0 și 1. Rezultatul poate fi interpretat ca o **probabilitate**. Dacă rezultatul este 0.85, înseamnă că modelul este 85% sigur că răspunsul este 1.

Cel mai mare avantaj al ei? Curba este lină și continuă, ceea ce ne va permite mai târziu să calculăm derivate și să antrenăm modelul inteligent folosind **Gradient Descent** (Coborârea pe gradient).

$$\sigma(z) = \frac{1}{1 + e^{-z}}$$


In [ ]:
def sigmoid_function(z):
    # Folosim funcția exponențială din numpy: np.exp()
    return ...

y_sigmoid = sigmoid_function(z_valori)

plt.plot(z_valori, y_sigmoid, linewidth=3, color='green')
plt.title("Funcția Sigmoid")
# Adăugăm o linie punctată pentru pragul de decizie (0.5)
plt.axhline(0.5, color='gray', linestyle='--')
plt.grid(True)
plt.show()

### De la o decizie la mai multe:

Până acum, perceptronul nostru lua o singură decizie. Aveam un singur set de ponderi ($W$) și un singur bias ($b$).

Dar ce facem dacă vrem să clasificăm imagini în **3 categorii diferite** (ex: Pisică, Câine, Pasăre)?
Răspunsul este simplu: construim **3 neuroni**, câte unul pentru fiecare clasă! Fiecare neuron va învăța la ce caracteristici trebuie să fie atent pentru clasa lui specifică.

Din punct de vedere matematic, asta înseamnă că matricea noastră de ponderi $W$ primește **o coloană nouă pentru fiecare clasă**.

* Intrările $A$ rămân la fel (ex: 3 poze $\times$ 2 caracteristici).
* Matricea $W$ va avea 2 linii (pentru caracteristici) și **3 coloane** (pentru cele 3 clase).
* Bias-ul $b$ nu mai este un singur număr, ci un șir de **3 numere** (câte un prag pentru fiecare clasă).

Partea frumoasă? Formula de bază rămâne absolut identică: $Z = A \cdot W + b$. Diferența este că acum $Z$ nu va mai fi o singură coloană de numere, ci o matrice cu 3 coloane de scoruri brute (numite *logits*).

In [2]:

import numpy as np

# A: 3 exemple (poze), fiecare cu 2 caracteristici (ex: greutate, înălțime)
# Forma matricei este (3, 2)
A = np.array([[1.5, 2.0],
              [2.0, 1.0],
              [3.5, 3.0]])

# W: Matricea de ponderi. Are 2 caracteristici (linii) x 3 clase (coloane).
# - Coloana 0 (Pisică): cum combinăm greutatea și înălțimea pentru a detecta o pisică
# - Coloana 1 (Câine): cum le combinăm pentru câine
# - Coloana 2 (Pasăre): cum le combinăm pentru pasăre
W = np.array([[ 0.5, -0.1,  0.8],
              [-0.2,  0.4, -0.5]]) # Forma matricei este (2, 3)

# b: Bias-ul are acum 3 valori (câte un prag pentru fiecare clasă)
b = np.array([0.1, 0.0, -0.2]) # Forma este (3,)

# Calculăm combinația liniară (înmulțirea matricială)
Z = A@W+b

print("Matricea de scoruri brute (Z):")
print(Z)
print(f"\nForma matricei Z este: {Z.shape} -> (3 exemple x 3 clase)")

Matricea de scoruri brute (Z):
[[4.50000000e-01 6.50000000e-01 1.66533454e-16]
 [9.00000000e-01 2.00000000e-01 9.00000000e-01]
 [1.25000000e+00 8.50000000e-01 1.10000000e+00]]

Forma matricei Z este: (3, 3) -> (3 exemple x 3 clase)


### Cum interpretăm aceste scoruri? Introducerea funcției Softmax

Dacă ai rulat codul de mai sus, vei vedea că pentru prima poză (primul rând din $Z$), scorurile arată cam așa: `[0.45, 0.65, 0.0]`. Acestea sunt numere oarecare. Pentru a lua o decizie, am vrea să știm *cât la sută* este sigur modelul că poza 1 este un Câine (clasa din mijloc, care are scorul cel mai mare).

Aici intervine funcția **Softmax**. Ea ia un rând de scoruri brute și face două lucruri:

1. Aplică funcția exponențială ($e^z$) pentru a transforma toate numerele (chiar și cele negative) în numere strict pozitive.
2. Împarte fiecare valoare la suma totală a rândului, transformându-le astfel în probabilități care adunate dau $1.0$ (sau 100%).

Formula pentru clasa $i$ este:


$$\text{Softmax}(z_i) = \frac{e^{z_i}}{\sum_{j=1}^{K} e^{z_j}}$$

In [3]:
def softmax(Z):
    """
    Aplică Softmax pe fiecare rând (exemplu) al unei matrice de scoruri.
    """
    # 1. Calculăm e^z pentru toată matricea
    exp_Z = ...

    # 2. Calculăm suma pe fiecare rând (axis=1)
    # keepdims=True menține forma matricei pentru a putea face împărțirea corect
    suma_pe_rand = ...

    # 3. Împărțim fiecare element la suma rândului său
    probabilitati = ...

    return probabilitati

# Calculăm probabilitățile pentru scorurile noastre Z
P = softmax(Z)

# Setăm numpy să afișeze numerele mai frumos, cu 2 zecimale
np.set_printoptions(precision=2, suppress=True)

print("Matricea de probabilități (P):")
print(P)

print("\nVerificare: Suma probabilităților pentru primul exemplu este:", np.sum(P[0]))


Matricea de probabilități (P):
[[0.35 0.43 0.22]
 [0.4  0.2  0.4 ]
 [0.4  0.26 0.34]]

Verificare: Suma probabilităților pentru primul exemplu este: 1.0


### Cum știe modelul dacă a greșit? Funcția de Cost (Loss)

Am obținut niște predicții, dar modelul abia s-a "născut". Ponderile ($W$) cu care am început au fost alese la întâmplare, deci probabil a ghicit prost.

Ca să poată învăța, modelul are nevoie de o notă. Trebuie să îi spunem matematic cât de tare a dat greș. Această "notă" se numește **Funcție de Cost (Loss Function)**.

* Dacă eroarea (Loss) este mare $\rightarrow$ modelul a greșit grav.
* Dacă eroarea (Loss) este aproape 0 $\rightarrow$ modelul este perfect.

Scopul întregului algoritm de Machine Learning este **să minimizeze acest Loss**.

---

### Cum arată realitatea? (One-Hot Encoding)

Pentru a calcula greșeala, trebuie să comparăm predicția modelului cu realitatea (răspunsul corect din baza de date).

Să ne amintim clasele noastre: 0 = Pisică, 1 = Câine, 2 = Pasăre.
Dacă poza numărul 1 este cu adevărat un Câine, nu putem scrie pur și simplu "1". O transformăm într-un vector care arată 100% sigur pe poziția Câinelui și 0 pe restul. Această tehnică se numește **One-Hot Encoding**:

* Adevărul pentru Câine: `[0, 1, 0]`

Dacă modelul a prezis `[0.1, 0.8, 0.1]`, eroarea va fi mică, pentru că 0.8 este aproape de 1.
Dacă modelul a prezis `[0.9, 0.05, 0.05]`, eroarea trebuie să fie uriașă, pentru că a fost sigur că e Pisică (0.9), când de fapt era Câine.

### Cross-Entropy (Entropia Încrucișată)

O funcție matematică pentru a măsura distanța dintre două probabilități este **Cross-Entropy**.

Ea funcționează astfel: se uită *doar* la probabilitatea pe care modelul a dat-o clasei corecte. Apoi, aplică un **logaritm** (mai exact, logaritm natural). Logaritmul ajuta prin prorpietatiile sale: pedepsește foarte, foarte dur un model care este "extrem de sigur, dar greșește".

Formula matematică pe un singur exemplu este:


$$\text{Loss} = - \sum_{i=1}^{K} Y_i \cdot \log(P_i)$$

Unde:

* $Y_i$ este valoarea reală (1 pentru clasa corectă, 0 pentru restul).
* $P_i$ este probabilitatea prezisă de model.

Fiindcă în $Y$ avem un singur 1 și restul sunt 0, formula calculează practic doar: `-log(probabilitatea_clasei_corecte)`.

In [ ]:
import numpy as np

# Să presupunem că avem următoarele probabilități prezise (P) pentru 3 poze
# Am obținut asta la pasul anterior cu Softmax
P_prezis = np.array([
    [0.10, 0.80, 0.10],  # Poza 1: Modelul e sigur că e Câine (80%)
    [0.70, 0.20, 0.10],  # Poza 2: Modelul e sigur că e Pisică (70%)
    [0.60, 0.30, 0.10]   # Poza 3: Modelul zice Pisică (60%)
])

# Răspunsurile corecte (Adevărul) encodate One-Hot
# Realitatea: Poza 1 e Câine, Poza 2 e Pisică, Poza 3 e PASĂRE!
Y_adevarat = np.array([
    [0, 1, 0],  # Corect: Câine
    [1, 0, 0],  # Corect: Pisică
    [0, 0, 1]   # Corect: Pasăre (Aici modelul a dat o probabilitate de doar 10%!)
])

def cross_entropy_loss(Y, P):
    """
    Calculează media erorii Cross-Entropy pentru un întreg lot de date.
    """
    # Adăugăm o valoare microscopică (epsilon) pentru a nu face log(0),
    # deoarece log(0) tinde la infinit și ne va da eroare în Python.
    epsilon = 1e-9

    # 1. Calculăm eroarea pentru fiecare exemplu: - Y * log(P)
    # np.sum(..., axis=1) face suma pe rânduri
    erori_individuale = -np.sum(..., axis=1)

    # 2. Facem media erorilor pentru tot lotul (batch-ul) de 3 poze
    loss_total = np.mean(erori_individuale)

    return loss_total, erori_individuale

# --- Testăm codul ---
loss_mediu, erori = cross_entropy_loss(Y_adevarat, P_prezis)

print("Erorile individuale pentru fiecare poză:")
print(f"Poza 1 (Corect): {erori[0]:.4f} -> Eroare mică")
print(f"Poza 2 (Corect): {erori[1]:.4f} -> Eroare mică")
print(f"Poza 3 (Greșit): {erori[2]:.4f} -> Eroare FOARTE MARE!")

print("-" * 40)
print(f"Eroarea medie finală (Loss) pentru tot lotul: {loss_mediu:.4f}")

### Coborârea pe Gradient (Gradient Descent): Cum învățăm din greșeli?

Avem eroarea (Loss-ul). Acum ce facem cu ea? Cum modificăm ponderile $W$ și bias-ul $b$ ca data viitoare să greșească mai puțin?

Imaginează-ți că ești legat la ochi pe un munte și vrei să ajungi în vale (acolo unde eroarea este zero). Nu vezi tot muntele, dar poți pipăi cu piciorul panta pământului. Dacă simți că panta urcă în față, faci un pas în spate.

În matematică, această "pantă" se numește **Gradient**. Gradientul ne arată direcția în care eroarea *crește*. Noi vrem să minimizăm eroarea, așa că vom face un pas în direcția *opusă* gradientului.

**Secretul magic al matematicii:**
Datorită modului inteligent în care am ales funcțiile (Softmax + Cross-Entropy), derivata lor combinată se simplifică la o formulă incredibil de elegantă.
"Panta" sau eroarea directă la nivelul predicției este pur și simplu diferența dintre ce am prezis și ce trebuia să fie:


$$\text{Eroare} = P - Y$$

Pentru a afla cum trebuie să modificăm $W$, înmulțim datele de intrare $A$ cu această eroare. Iar mărimea "pasului" pe care îl facem pe munte este controlată de un număr mic numit **Rata de învățare (Learning Rate, $\alpha$)**.

Formulele de actualizare:

1. Calculăm gradientul pentru ponderi: $grad\_W = \frac{1}{N} A^T \cdot (P - Y)$
2. Actualizăm ponderile: $W = W - \alpha \cdot grad\_W$

In [ ]:

### Un singur pas de gradient descent

import numpy as np

# Avem datele noastre (3 poze, 2 caracteristici)
A = np.array([[1.5, 2.0], [2.0, 1.0], [3.5, 3.0]])
N = A.shape[0] # Numărul de exemple (3)

# Ponderile și predicțiile de la pasul anterior
W = np.array([[ 0.5, -0.1,  0.8], [-0.2,  0.4, -0.5]])
b = np.array([0.1, 0.0, -0.2])

P_prezis = np.array([[0.10, 0.80, 0.10], [0.70, 0.20, 0.10], [0.60, 0.30, 0.10]])
Y_adevarat = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

# Setăm mărimea pasului (Learning Rate)
learning_rate = ...

print("Ponderile W ÎNAINTE de actualizare:")
print(W)

# 1. Calculăm diferența simplă (P - Y)
eroare_Z = ...

# 2. Calculăm gradientul pentru W (A transpus înmulțit matriceal cu eroarea_Z)
# Împărțim la N pentru a face o medie pe tot lotul (batch)
grad_W = (A.T @ eroare_Z) / N

# Gradientul pentru bias (media erorilor pe coloane)
grad_b = ...

# 3. FACEM PASUL! Actualizăm ponderile scăzând gradientul
W_nou = ...
b_nou = ...

print("\nPonderile W DUPĂ un pas de Gradient Descent:")
print(W_nou)
# Vei observa că valorile s-au modificat ușor în direcția corectă!

### Antrenamentul Complet: Bucla For (Epocile)


Un singur pas nu ne va duce până în vale. Trebuie să repetăm acest proces (Forward Pass $\rightarrow$ Calcul Eroare $\rightarrow$ Backward Pass / Actualizare) de zeci, sute sau mii de ori.

O trecere completă prin toate datele noastre de antrenament se numește **Epocă (Epoch)**.
Pentru a pune tot cap la cap, vom scrie o buclă `for` care va rula întregul pipeline de un număr maxim de epoci, și vom printa eroarea pe parcurs ca să vedem cum modelul devine din ce în ce mai inteligent.

In [ ]:

# Re-definim funcția softmax de mai devreme pentru a fi siguri că o avem la îndemână
def softmax(Z):
    ...

# Datele noastre de intrare și răspunsurile corecte
A = np.array([[1.5, 2.0], [2.0, 1.0], [3.5, 3.0]])
Y_adevarat = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
N = A.shape[0]

# 1. Inițializăm ponderile cu zero sau valori foarte mici la începutul antrenamentului
# Avem 2 trăsături și 3 clase, deci W va fi de 2x3
W = np.zeros((2, 3))
b = np.zeros(3)

# Parametrii de antrenare
max_epochs = 10
learning_rate = 0.1
epsilon = 1e-9 # Pentru a evita log(0)

print("Începem antrenamentul...\n")

for epoch in range(max_epochs):
    # --- Forward Pass (Luăm o decizie cu "creierul" curent) ---
    Z = A @ W + b
    P = softmax(Z)

    # --- Calculăm Eroarea (Cât de tare am greșit?) ---
    # --- Cross-Entropy Loss ---
    erori_individuale = ...
    loss_total = np.mean(erori_individuale)

    # Afișăm progresul din 10 în 10 epoci
    if epoch % 10 == 0 or epoch == max_epochs - 1:
        print(f"Epoca {epoch:3d} | Loss: {loss_total:.4f}")

    # --- Backward Pass (Calculăm gradienții) ---
    eroare_Z = ...
    grad_W = (A.T @ eroare_Z) / N
    grad_b = ...

    # --- Actualizăm ponderile ---
    W = ...
    b = ...

print("\nAntrenament terminat!")
print("\nVerificăm predicțiile finale (probabilitățile):")
Z_final = A @ W + b
P_final = softmax(Z_final)
np.set_printoptions(precision=3, suppress=True)
print(P_final)

# Să vedem ce alege modelul la final
predictii_finale = np.argmax(P_final, axis=1)
adevarul_absolut = np.argmax(Y_adevarat, axis=1)

print(f"\nPredicțiile modelului: {predictii_finale}")
print(f"Răspunsurile reale:    {adevarul_absolut}")